/* This file was generated by SableCC (http://www.sablecc.org/). */

using System;
using System.Collections;
using System.Text;
using System.IO;
using CS426.lexer;
using CS426.node;

class TestLexer
{
  public static void Main(String[] args)
    {
        try
        {
            Lexer l = new Lexer(new StreamReader(args[0]));
            while (true)
            {
                Token token = l.Next();
                Console.WriteLine("Read token '" + token.GetType().Name +
                    "', Text = [" + token.Text + "] at [" + token.Line +
                    "," + token.Pos + "]");
                if (token is EOF) break;
            }
        } catch (Exception e)
        {
            Console.WriteLine(e.ToString());

        }
    

    //Console.ReadLine();
  }
}
